### ISSUE TITLE
Problems with widget design

### ISSUE THREAD

**Issue by KOT040188** [Risu/CoolPopupQuicklaunch#1]
I use a dark theme.  The widget looks very ugly http://imgur.com/a/I9Fu9QZ In addition, there is no smooth animation of the opening, which is in other widgets.  It can be fixed?  Kde neon, plasma 5.17, v1.2.

**Comment by Risu** [comment]
You can change the text colour in settings ("Configure.." from right click menu). Background colour is related to the system theme. Icons are supported from 'links to applications'. To support icons from other shortcuts a native script/DLL is required (which is not problem in self, but I am not intending to support recompilation or installation script, so this is not included).
Next version is planned in December, after that I will look into animation.
To keep an open issue please address one specific problem per topic.

**Comment by roke-julian-lockhart** [comment]
@KOT040188, I agree, because I believe that adherence to the colouration of the host is important, because when I replace my theme, I do not want to manually modify the values that this widget adheres to.

Consequently, @Risu, if that customization is desirable, I propose that a check-box be added that allows it to adhere to the current Plasma theme. ...and potentially enable it by default?
